name: Auto Merge
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: shouichi/github-action-merge-dependabot@github-auto-merge
        with:
          github-token: ${{ github.token }}
          enable-auto-merge: true
